/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ctbs;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.AWTEventListener;
import javax.swing.*;
import ctbs.SIGN_UP;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;



/**
 *
 * @author ujwal
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtuname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtpwd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().setLayout(null);

        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });
        getContentPane().add(txtuname);
        txtuname.setBounds(610, 320, 220, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 490, 120, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("SIGN UP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 570, 120, 40);
        getContentPane().add(txtpwd);
        txtpwd.setBounds(610, 380, 160, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("CRICKET TICKET BOOKING SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 220, 440, 40);

        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 330, 110, 10);

        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(480, 390, 110, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String un =txtuname.getText();
        String pwd =txtpwd.getText();
        if("admin".equals(un) && "admin".equals(pwd))
          { 
              JOptionPane.showMessageDialog(null,"admin login!!!");
               ADMIN infi=new ADMIN();
          infi.setVisible(true);
               infi.setExtendedState(infi.getExtendedState() | JFrame.MAXIMIZED_BOTH);
               dispose();
          }
        
        
        else if("".equals(un) || "".equals(pwd))
          { 
              JOptionPane.showMessageDialog(null,"User name amnd password cannot be empty!!!");
              return;
          }

        else{
      try{  
Class.forName("com.mysql.jdbc.Driver");  
Connection con=DriverManager.getConnection(  
"jdbc:mysql://localhost:3306/ctbsdb","root","password");  

Statement stmt=con.createStatement();  


ResultSet rs=stmt.executeQuery("select *from signup where name='"+un+"' and password='"+pwd+"' ;");  
//ResultSet rs=stmt.executeQuery("select *from signup where name='one' and password='one' ;");  
 if(rs.next()){
  
       JOptionPane.showMessageDialog(null,"Logged in succesfully!!!");
        // b.setVisible(true);
        
String svip;
 String sfc;
 String sgallery;
//getting vip value 
System.out.println("here");
ResultSet rs3=stmt.executeQuery("select vip from seats;");  
System.out.println("here2"); 
rs3.first();
 System.out.println("here3");
System.out.println(rs3.getString(1)); 
    svip = rs3.getString(1);
     System.out.println(svip);
   
  System.out.println("here4");   
     
               
ResultSet rs1=stmt.executeQuery("select fc from seats;");  
 
 rs1.first();
     
    sfc = rs1.getString(1);
              
 

 ResultSet rs2=stmt.executeQuery("select gallery from seats;");  
 
 rs2.first();
    
    sgallery = rs2.getString(1);
          BOOKING111 myFrame = new BOOKING111(svip,sfc,sgallery,un);
                      myFrame.setVisible(true);
                      myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
               dispose();  
               
   //new BOOKING111(svip,sfc,sgallery,un).setVisible(true);
//con.close();  
//}catch(Exception e){ System.out.println(e);}  



        
}  
else{
    JOptionPane.showMessageDialog(null,"NOT succesful!!!");
}

//System.out.println(rs.getString(1));  
con.close();  
}catch(Exception e){ System.out.println(e);}  

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SIGN_UP infi=new SIGN_UP();
          infi.setVisible(true);
               infi.setExtendedState(infi.getExtendedState() | JFrame.MAXIMIZED_BOTH);
   
          dispose();
          
          
//           HOME myFrame=new HOME();
//                myFrame.setVisible(true);
//             myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            
          
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HOME myFrame=new HOME();
                myFrame.setVisible(true);
             myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtpwd;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
