/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ctbs;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.AWTEventListener;
import javax.swing.*;
import ctbs.SIGN_UP;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import ctbs.BOOKING111;


/**
 *
 * @author ujwal
 */
public class SIGN_UP extends javax.swing.JFrame {

    /**
     * Creates new form SIGN_UP
     */
    public SIGN_UP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtphno = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtpwd = new javax.swing.JTextField();
        txtcpwd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(null);
        setSize(new java.awt.Dimension(1000, 1000));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 270, 110, 10);

        jLabel3.setText("PHONE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 310, 90, 20);

        jLabel4.setText("EMAIL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 360, 110, 10);

        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 400, 110, 10);

        jLabel6.setText("CONFIRM PASSWORD ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 440, 160, 10);
        getContentPane().add(txtname);
        txtname.setBounds(540, 260, 230, 30);

        txtphno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtphno);
        txtphno.setBounds(540, 300, 230, 30);

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail);
        txtemail.setBounds(540, 350, 230, 30);

        txtpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwdActionPerformed(evt);
            }
        });
        getContentPane().add(txtpwd);
        txtpwd.setBounds(540, 390, 190, 30);

        txtcpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpwdActionPerformed(evt);
            }
        });
        getContentPane().add(txtcpwd);
        txtcpwd.setBounds(540, 430, 190, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 500, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("CRICKET TICKET BOOKING SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 210, 440, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(669, 500, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String un =txtname.getText();
        String phone =txtphno.getText();
        String email =txtemail.getText();
        String pwd =txtpwd.getText();
        String cpwd =txtcpwd.getText();
       //System.out.println(pwd);
       //System.out.println(cpwd);
       
      
        if("".equals(un) || "".equals(phone) || "".equals(email) || "".equals(pwd))
       {
           JOptionPane.showMessageDialog(null,"All fields are mandatory");
           return;
       }
        
//       
        if(!(phone.matches("\\d{10}")) )
                {
            JOptionPane.showMessageDialog(null,"Phone number must be of 10 digits, invalid phone number");
           return;
}
        
//        if(!(email.matches("^[a-z]*[0-9]@^[a-z].com")))
        if(!(email.matches("[a-zA-z]+[0-9]*[a-zA-Z]*@[a-zA-Z]+.com")))
        {
 
            JOptionPane.showMessageDialog(null,"Email is invalid");
           return;

        }
       if(!pwd.equals(cpwd))
      {
          JOptionPane.showMessageDialog(null,"Password and confirm password must be same");
         // SIGN_UP info=new SIGN_UP();
          //info.setVisible(true);
          
      }
       else
      {JOptionPane.showMessageDialog(null,"Signed up successfully!");
      try{  
Class.forName("com.mysql.jdbc.Driver");  
Connection con=DriverManager.getConnection(  
"jdbc:mysql://localhost:3306/ctbsdb","root","password");  
//here sonoo is database name, root is username and password  
Statement stmt=con.createStatement();  
 //String insert="INSERT INTO signup VALUES('"+un+"','"+phone+"','"+email+"','"+pwd+"','"+cpwd+"');";
 //String insert="select *from signup";
//ResultSet rs=stmt.executeUpdate("INSERT INTO signup VALUES('"+un+"','"+phone+"','"+email+"','"+pwd+"','"+cpwd+"');");  
stmt.executeUpdate("INSERT INTO signup VALUES('"+un+"','"+phone+"','"+email+"','"+pwd+"','"+cpwd+"');");  
 //ResultSet rs=stmt.executeQuery("insert");  
//while(rs.next())  
//System.out.println(rs.getString(1));  
con.close();  
}catch(Exception e){ System.out.println(e);}  
      
      
      
        try{  
Class.forName("com.mysql.jdbc.Driver");  
Connection con=DriverManager.getConnection(  
"jdbc:mysql://localhost:3306/ctbsdb","root","password");  
String svip;
 String sfc;
 String sgallery;
Statement stmt=con.createStatement();  
//getting vip value 

ResultSet rs=stmt.executeQuery("select vip from seats;");  
 rs.first();
System.out.println(rs.getString(1)); 
    svip = rs.getString(1);
     System.out.println(svip);
     
     
     
               
ResultSet rs1=stmt.executeQuery("select fc from seats;");  
 
 rs1.first();
     
    sfc = rs1.getString(1);
              
 

 ResultSet rs2=stmt.executeQuery("select gallery from seats;");  
 
 rs2.first();
    
    sgallery = rs2.getString(1);
              BOOKING111 myFrame = new BOOKING111(svip,sfc,sgallery,un);
                      myFrame.setVisible(true);
                      myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
               dispose();
   //new BOOKING111(svip,sfc,sgallery,un).setVisible(true);
con.close();  
}catch(Exception e){ System.out.println(e);}  

      
      /*
      
      
                      BOOKING111 myFrame = new BOOKING111();
                      myFrame.setVisible(true);
                      myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
      
                    */
                      
      
      }
      
       
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtphnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphnoActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpwdActionPerformed

    private void txtcpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpwdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
  HOME myFrame=new HOME();
                myFrame.setVisible(true);
             myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
             dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGN_UP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGN_UP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGN_UP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGN_UP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                   // new SIGN_UP().setVisible(true);
                    SIGN_UP myFrame = new SIGN_UP();
                    myFrame.setVisible(true);
                    myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
                                 
                
                
                
                }
            
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtcpwd;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphno;
    private javax.swing.JTextField txtpwd;
    // End of variables declaration//GEN-END:variables
}
